WITH d AS (
	SELECT "CODGEO",
		   regexp_replace('pop_2_5_ans_p,' || "POP0205_P" || ',
						pop_6_10_ans_p,' || "POP0610_P" || ',
						pop_11_14_ans_p,' || "POP1114_P" || ',
						pop_15_17_ans_p,' || "POP1517_P" || ',
						pop_18_24_ans_p,' || "POP1824_P" || ',
						pop_25_29_ans_p,' || "POP2529_P" || ',
						pop_30_ans_plus_p,' || "POP30P_P" || ',
						pop_scolarisee_2_5_ans_p,' || "SCOL0205_P" || ',
						pop_scolarisee_6_10_ans_p,' || "SCOL0610_P" || ',
						pop_scolarisee_11_14_ans_p,' || "SCOL1114_P" || ',
						pop_scolarisee_15_17_ans_p,' || "SCOL1517_P" || ',
						pop_scolarisee_18_24_ans_p,' || "SCOL1824_P" || ',
						pop_scolarisee_25_29_ans_p,' || "SCOL2529_P" || ',
						pop_scolarisee_30_ans_plus_p,' || "SCOL30P_P" || ',
						hommes_2_5_ans_p,' || "H0205_P" ||',
						hommes_6_10_ans_p,' || "H0610_P" ||',
						hommes_11_14_ans_p,' || "H1114_P" ||',
						hommes_15_17_ans_p,' || "H1517_P" ||',
						hommes_18_24_ans_p,' || "H1824_P" ||',
						hommes_25_29_ans_p,' || "H2529_P" ||',
						hommes_30_ans_ou_plus_p,' || "H30P_P" ||',
						hommes_scolarises_2_5_ans_p,' || "HSCOL0205_P" ||',
						hommes_scolarises_6_10_ans_p,' || "HSCOL0610_P" ||',
						hommes_scolarises_11_14_ans_p,' || "HSCOL1114_P" ||',
						hommes_scolarises_15_17_ans_p,' || "HSCOL1517_P" ||',
						hommes_scolarises_18_24_ans_p,' || "HSCOL1824_P" ||',
						hommes_scolarises_25_29_ans_p,' || "HSCOL2529_P" ||',
						hommes_scolarises_30_ans_ou_plus_p,' || "HSCOL30P_P" ||',
						femmes_2_5_ans_p,' || "F0205_P" ||',
						femmes_6_10_ans_p,' || "F0610_P" ||',
						femmes_11_14_ans_p,' || "F1114_P" ||',
						femmes_15_17_ans_p,' || "F1517_P" ||',
						femmes_18_24_ans_p,' || "F1824_P" ||',
						femmes_25_29_ans_p,' || "F2529_P" ||',
						femmes_30_ans_ou_plus_p,' || "F30P_P" ||',
						femmes_scolarises_2_5_ans_p,' || "FSCOL0205_P" ||',
						femmes_scolarises_6_10_ans_p,' || "FSCOL0610_P" ||',
						femmes_scolarises_11_14_ans_p,' || "FSCOL1114_P" ||',
						femmes_scolarises_15_17_ans_p,' || "FSCOL1517_P" ||',
						femmes_scolarises_18_24_ans_p,' || "FSCOL1824_P" ||',
						femmes_scolarises_25_29_ans_p,' || "FSCOL2529_P" ||',
						femmes_scolarises_30_ans_ou_plus_p,' || "FSCOL30P_P" ||',
						nb_pers_non_scolarisees_15ans_plus_p,' || "NSCOL15P_P" || ',
						nb_pers_non_scolarisees_15ans_plus_sans_diplome_cep_p,' || "NSCOL15P_DIPLMIN_P" || ',
						nb_pers_non_scolarisees_15ans_plus_brevet_bepc_dnb_p,' || "NSCOL15P_BEPC_P" || ',
						nb_pers_non_scolarisees_15ans_plus_cap_bep_p,' || "NSCOL15P_CAPBEP_P" || ',
						nb_pers_non_scolarisees_15ans_plus_bac_brevet_professionnel_p,' || "NSCOL15P_BAC_P" || ',
						nb_pers_non_scolarisees_15ans_plus_bac_plus_2_p,' || "NSCOL15P_SUP2_P" || ',
						nb_pers_non_scolarisees_15ans_plus_bac_plus_3_4_p,' || "NSCOL15P_SUP34_P" || ',
						nb_pers_non_scolarisees_15ans_plus_bac_plus_5_plus_p,' || "NSCOL15P_SUP5_P" || ',
						nb_hommes_non_scolarisees_15ans_plus_p,' || "HNSCOL15P_P" || ',
						nb_hommes_non_scolarisees_15ans_plus_sans_diplome_cep_p,' || "HNSCOL15P_DIPLMIN_P" || ',
						nb_hommes_non_scolarisees_15ans_plus_brevet_bepc_dnb_p,' || "HNSCOL15P_BEPC_P" || ',
						nb_hommes_non_scolarisees_15ans_plus_cap_bep_p,' || "HNSCOL15P_CAPBEP_P" || ',
						nb_hommes_non_scolarisees_15ans_plus_bac_brevet_professionnel_p,' || "HNSCOL15P_BAC_P" || ',
						nb_hommes_non_scolarisees_15ans_plus_bac_plus_2_p,' || "HNSCOL15P_SUP2_P" || ',
						nb_hommes_non_scolarisees_15ans_plus_bac_plus_3_4_p,' || "HNSCOL15P_SUP34_P" || ',
						nb_hommes_non_scolarisees_15ans_plus_bac_plus_5_plus_p,' || "HNSCOL15P_SUP5_P" || ',
						nb_femmes_non_scolarisees_15ans_plus_p,' || "FNSCOL15P_P" || ',
						nb_femmes_non_scolarisees_15ans_plus_sans_diplome_cep_p,' || "FNSCOL15P_DIPLMIN_P" || ',
						nb_femmes_non_scolarisees_15ans_plus_brevet_bepc_dnb_p,' || "FNSCOL15P_BEPC_P" || ',
						nb_femmes_non_scolarisees_15ans_plus_cap_bep_p,' || "FNSCOL15P_CAPBEP_P" || ',
						nb_femmes_non_scolarisees_15ans_plus_bac_brevet_professionnel_p,' || "FNSCOL15P_BAC_P" || ',
						nb_femmes_non_scolarisees_15ans_plus_bac_plus_2_p,' || "FNSCOL15P_SUP2_P" || ',
						nb_femmes_non_scolarisees_15ans_plus_bac_plus_3_4_p,' || "FNSCOL15P_SUP34_P" || ',
						nb_femmes_non_scolarisees_15ans_plus_bac_plus_5_plus_p,' || "FNSCOL15P_SUP5_P",
					E'[\t\n\r]','','g') AS data
	FROM insee.rp_formation_import
)
INSERT INTO insee.donnees_communes("annee","fk_base","donnees", "code_commune")
SELECT
	   2020,
	   4,
	   jsonb_object(string_to_array(data::text,',')),
	   "CODGEO"
FROM d
ORDER BY "CODGEO"
