WITH d AS (
	SELECT "CODGEO",
		   regexp_replace('actifs_occupes_15ans_plus_p,' || "ACTOCC15P_P" || ',
						salaries_15ans_plus_p,' || "SAL15P_P" || ',
						non_salaries_15ans_plus_p,' || "NSAL15P_P" || ',
						actifs_occupes_15ans_plus_temps_partiel_p,' || "ACTOCC15P_TP_P" || ',
						salaries_15_ans_plus_temps_partiel_p,' || "SAL15P_TP_P" || ',
						salaries_15_ans_plus_temps_partiel_hommes_p,' || "HSAL15P_TP_P" || ',
						salaries_15_ans_plus_temps_partiel_femmes_p,' || "FSAL15P_TP_P" || ',
						non_salaries_15_ans_plus_temps_partiel_p,' || "NSAL15P_TP_P" || ',
						actifs_occupes_15ans_plus_hommes_p,' || "HACTOCC15P_P" || ',
						salaries_15ans_plus_hommes_p,' || "HSAL15P_P" || ',
						salaries_15ans_plus_cdi_fonc_publique_hommes_p,' || "HSAL15P_CDI_P" || ',
						salaries_15ans_plus_cdd_hommes_p,' || "HSAL15P_CDD_P" || ',
						salaries_15ans_plus_interim_hommes_p,' || "HSAL15P_INTERIM_P" || ',
						salaries_15ans_plus_emplois_aides_hommes_p,' || "HSAL15P_EMPAID_P" || ',
						salaries_15ans_plus_apprentissage_stages_hommes_p,' || "HSAL15P_APPR_P" || ',
						non_salaries_15ans_plus_hommes_p,' || "HNSAL15P_P" || ',
						non_salaries_15ans_plus_independants_hommes_p,' || "HNSAL15P_INDEP_P" || ',
						non_salaries_15ans_plus_employeurs_hommes_p,' || "HNSAL15P_EMPLOY_P" || ',
						non_salaries_15ans_plus_aides_familiaux_hommes_p,' || "HNSAL15P_AIDFAM_P" || ',
						actifs_occupes_15ans_plus_femmes_p,' || "FACTOCC15P_P" || ',
						salaries_15ans_plus_femmes_p,' || "FSAL15P_P" || ',
						salaries_15ans_plus_cdi_fonc_publique_femmes_p,' || "FSAL15P_CDI_P" || ',
						salaries_15ans_plus_cdd_femmes_p,' || "FSAL15P_CDD_P" || ',
						salaries_15ans_plus_interim_femmes_p,' || "FSAL15P_INTERIM_P" || ',
						salaries_15ans_plus_emplois_aides_femmes_p,' || "FSAL15P_EMPAID_P" || ',
						salaries_15ans_plus_apprentissage_stages_femmes_p,' || "FSAL15P_APPR_P" || ',
						non_salaries_15ans_plus_femmes_p,' || "FNSAL15P_P" || ',
						non_salaries_15ans_plus_independants_femmes_p,' || "FNSAL15P_INDEP_P" || ',
						non_salaries_15ans_plus_eployeurs_femmes_p,' || "FNSAL15P_EMPLOY_P" || ',
						non_salaries_15ans_plus_aides_familiaux_femmes_p,' || "FNSAL15P_AIDFAM_P" || ',
						salaries_15_64ans_hommes_p,' || "HSAL1564_P" || ',
						salaries_15_24ans_hommes_p,' || "HSAL1524_P" || ',
						salaries_25_54ans_hommes_p,' || "HSAL2554_P" || ',
						salaries_55_64ans_hommes_p,' || "HSAL5564_P" || ',
						salaries_15_64ans_temps_partiel_hommes_p,' || "HSAL1564_TP_P" || ',
						salaries_15_24ans_temps_partiel_hommes_p,' || "HSAL1524_TP_P" || ',
						salaries_25_54ans_temps_partiel_hommes_p,' || "HSAL2554_TP_P" || ',
						salaries_55_64ans_temps_partiel_hommes_p,' || "HSAL5564_TP_P" || ',
						salaries_15_64ans_femmes_p,' || "FSAL1564_P" || ',
						salaries_15_24ans_femmes_p,' || "FSAL1524_P" || ',
						salaries_25_54ans_femmes_p,' || "FSAL2554_P" || ',
						salaries_55_64ans_femmes_p,' || "FSAL5564_P" || ',
						salaries_15_64ans_temps_partiel_femmes_p,' || "FSAL1564_TP_P" || ',
						salaries_15_24ans_temps_partiel_femmes_p,' || "FSAL1524_TP_P" || ',
						salaries_25_54ans_temps_partiel_femmes_p,' || "FSAL2554_TP_P" || ',
						salaries_55_64ans_temps_partiel_femmes_p,' || "FSAL5564_TP_P" || ',						
						actifs_occupes_15_ans_plus_travaille_commune_residence_p,' || "ACTOCC15P_ILT1_P" || ',
						actifs_occupes_15_ans_plus_travaille_commune_autre_residence_p,' || "ACTOCC15P_ILT2P_P" || ',
						actifs_occupes_15_ans_plus_travaille_autre_commune_meme_dpt_p,' || "ACTOCC15P_ILT2_P" || ',
						actifs_occupes_15_ans_plus_travaille_autre_dpt_meme_region_p,' || "ACTOCC15P_ILT3_P" || ',
						actifs_occupes_15_ans_plus_travaille_autre_region_en_metropole_p,' || "ACTOCC15P_ILT4_P" || ',
						actifs_occupes_15_ans_plus_travaille_autre_region_hors_metropole_p,' || "ACTOCC15P_ILT5_P" || ',
						actifs_occupes_15_ans_plus_pas_de_transport_c,' || "ACTOCC15P_PASTRANS_P" || ',
						actifs_occupes_15_ans_plus_marche_c,' ||"ACTOCC15P_MARCHE_P" || ',
						actifs_occupes_15_ans_plus_velo_c,' || "ACTOCC15P_VELO_P" || ',
						actifs_occupes_15_ans_2_roues_motorise_c,' || "ACTOCC15P_2ROUESMOT_P" || ',
						actifs_occupes_15_ans_plus_voiture_c,' || "ACTOCC15P_VOITURE_P" || ',
						actifs_occupes_15_ans_plus_transport_en_commun_c,' || "ACTOCC15P_COMMUN_P",
					E'[\t\n\r]','','g') AS data
	FROM insee.rp_emploi_import
)
INSERT INTO insee.donnees_communes("annee","fk_base","donnees", "code_commune")
SELECT
	   2020,
	   6,
	   jsonb_object(string_to_array(data::text,',')),
	   "CODGEO"
FROM d
ORDER BY "CODGEO"
