# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DonneesInsee
                                 A QGIS plugin
 This plugin download insee's data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-04
        copyright            : (C) 2024 by Thomas Szczurek-Gayant
        email                : thomas.szczurek@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Thomas Szczurek-Gayant'
__date__ = '2024-08-04'
__copyright__ = '(C) 2024 by Thomas Szczurek-Gayant'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DonneesInsee class from file DonneesInsee.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DonneesInsee import DonneesInseePlugin
    return DonneesInseePlugin()
